In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
df = pd.read_csv('emails.csv')
df.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [11]:
df.shape

(5728, 2)

In [4]:
df['spam'].value_counts()

spam
0    4360
1    1368
Name: count, dtype: int64

In [12]:
# there may be duplicate mails. so we drop the duplicates
df.drop_duplicates(inplace=True)

In [13]:
df # 1: spam, 0: ham

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5695 rows x 2 columns]

In [14]:
df['spam'].value_counts()

spam
0    4327
1    1368
Name: count, dtype: int64

In [15]:
df.isnull().sum()

text    0
spam    0
dtype: int64

### Separate X & Y

In [16]:
x = df.text.values
y = df.spam.values

(5695,)

### Train Test Split

In [54]:
from sklearn.model_selection import train_test_split

In [55]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.20, random_state=42)

### Data Preprocessing

In [56]:
from sklearn.feature_extraction.text import CountVectorizer

In [69]:
cv = CountVectorizer()

In [72]:
# fit_transform
x_train = cv.fit_transform(xtrain)

In [73]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [60]:
from sklearn.naive_bayes import MultinomialNB

In [88]:
multinb_model = MultinomialNB()

In [89]:
multinb_model.fit(x_train, ytrain)

MultinomialNB()

In [90]:
# don't fit_transform() again. Just transform()
x_test = cv.transform(xtest)

In [92]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [2, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [93]:
multinb_model.score(x_test, ytest)

0.9912203687445127

### create an email and have the model predict

In [100]:
emails = ['Hey, I want to learn ML asap. Wow!! you won an Iphone. do the survery to receive it...']

In [101]:
cv_emails = cv.transform(emails)

In [102]:
multinb_model.predict(cv_emails) # correctly predicted as a spam email

array([1], dtype=int64)

In [103]:
emails1 = ['Hello, Hope all is well with you and your family']

In [104]:
cv_emails1 = cv.transform(emails1)

In [105]:
multinb_model.predict(cv_emails1) # correctly predicted as a ham email 

array([0], dtype=int64)